In [ ]:
# with open('./drive/MyDrive/ReadME.md','w') as f:
#     data = f.write('*반가워요.')
#     print("저장되었습니다.")
# !pwd

# 넘파이 (numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

## 1차원과 속성들

In [6]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[3])
print(narry[2:4]) # <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [7]:
narr1 = np.array ([1,2,3,4])
narr2 = np.array ([1,2,'a','b'])
narr3 = np.array ([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [8]:
narr4 = np.zeros((2,2), dtype='int64')
narr6 = np.full((3,3),3)
narr5 = np.ones((2,2))
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype='int64') # 0에서 100을 포함해서 5가지
narr10 = np.arange(0,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [9]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape, arr1.size, type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [11]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim,'/데이터타입:',arr2.dtype,'/형태:',arr2.shape,'/크기:', arr2.size, type(arr2),arr2)
print('차원:',arr3.ndim,'/데이터타입:',arr3.dtype,'/형태:',arr3.shape,'/크기:', arr3.size, type(arr3),arr3)
print('차원:',arr4.ndim,'/데이터타입:',arr4.dtype,'/형태:',arr4.shape,'/크기:', arr4.size, type(arr4),arr4)
print('차원:',arr5.ndim,'/데이터타입:',arr5.dtype,'/형태:',arr5.shape,'/크기:', arr5.size, type(arr5),arr5)
print('차원:',arr6.ndim,'/데이터타입:',arr6.dtype,'/형태:',arr6.shape,'/크기:', arr6.size, type(arr6),arr6)

차원: 2 /데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 /데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 /데이터타입: int64 /형태: (2, 5) /크기: 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 /데이터타입: int64 /형태: (5, 2) /크기: 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 /데이터타입: int64 /형태: (3, 3, 3) /크기: 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
test1 = np.arange(1,22).reshape(3,7)
test2 = np.arange(1,8).reshape(7,1)
test3 = np.arange(1,11).reshape(5,2)
test4 = np.arange(1,22).reshape(3,7)
test5 = np.arange(1,13).reshape(4,3,1)
print(test1,"\n",'='*25)
print(test2,"\n",'='*25)
print(test3,"\n",'='*25)
print(test4,"\n",'='*25)
print(test5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [13]:
test1[1][2:5]

array([10, 11, 12])

In [14]:
print(test4[0][3:])
print(test4[1][3:])
print(test4[2][3:])

[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [15]:
test4[1:3,2:3]

array([[10],
       [17]])

In [16]:
test4

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [17]:
test4[0:3,3:7]

array([[ 4,  5,  6,  7],
       [11, 12, 13, 14],
       [18, 19, 20, 21]])

In [18]:
test4[1:3,4:6]

array([[12, 13],
       [19, 20]])

In [19]:
print(test4 > 12)
print(test4[test4 > 12])
print(test4 % 2 == 0)
print(test4[test4 % 2 == 0])

[[False False False False False False False]
 [False False False False False  True  True]
 [ True  True  True  True  True  True  True]]
[13 14 15 16 17 18 19 20 21]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]
[ 2  4  6  8 10 12 14 16 18 20]


In [20]:
# np 배열 연산 // shape 가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [21]:
# 브로드캐스팅
np3 = np1 + 10
print(np1)
print(np3)

[ 6  7  8  9 10]
[16 17 18 19 20]


In [22]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(3,1)
print(br1)
print(br2)
# 스칼라와 연산
print("=====스칼라와 연산=====")
print(br1)
print(br1+3)
print(br1*2)
# 2D와 1D의 연산
print("=====2D와 1D의 연산=====")
print(br2)
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11]
 [22]
 [33]]
=====스칼라와 연산=====
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=====2D와 1D의 연산=====
[[11]
 [22]
 [33]]
[[12 13 14]
 [26 27 28]
 [40 41 42]]
[[ 11  22  33]
 [ 88 110 132]
 [231 264 297]]


In [23]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten()) # flatten은 일자로 쭉 펴줌

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [24]:
# randomint
import numpy as np
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[111,  66, 185],
        [211, 254,  57],
        [ 60,  84, 166]],

       [[  2,  23,  72],
        [145,  45,  94],
        [210, 112, 147]],

       [[167, 103, 101],
        [108, 110,  47],
        [226,  48, 243]]], dtype=int32)

In [25]:
print('평균값:',np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 118.4074074074074 표준편차: 68.2610779283856 최소값: 2 최대값: 254


In [26]:
print(len(x.flatten()))

27


In [33]:
import numpy as np
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5,34,3,3,23,0,1,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
22
