In [ ]:
# with open('./drive/MyDrive/ReadME.md','w') as f:
#     data = f.write('*반가워요.')
#     print("저장되었습니다.")
# !pwd

# 넘파이 (numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

## 1차원과 속성들

In [6]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[3])
print(narry[2:4]) # <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [7]:
narr1 = np.array ([1,2,3,4])
narr2 = np.array ([1,2,'a','b'])
narr3 = np.array ([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [8]:
narr4 = np.zeros((2,2), dtype='int64')
narr6 = np.full((3,3),3)
narr5 = np.ones((2,2))
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype='int64') # 0에서 100을 포함해서 5가지
narr10 = np.arange(0,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [9]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape, arr1.size, type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [11]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim,'/데이터타입:',arr2.dtype,'/형태:',arr2.shape,'/크기:', arr2.size, type(arr2),arr2)
print('차원:',arr3.ndim,'/데이터타입:',arr3.dtype,'/형태:',arr3.shape,'/크기:', arr3.size, type(arr3),arr3)
print('차원:',arr4.ndim,'/데이터타입:',arr4.dtype,'/형태:',arr4.shape,'/크기:', arr4.size, type(arr4),arr4)
print('차원:',arr5.ndim,'/데이터타입:',arr5.dtype,'/형태:',arr5.shape,'/크기:', arr5.size, type(arr5),arr5)
print('차원:',arr6.ndim,'/데이터타입:',arr6.dtype,'/형태:',arr6.shape,'/크기:', arr6.size, type(arr6),arr6)

차원: 2 /데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 /데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 /데이터타입: int64 /형태: (2, 5) /크기: 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 /데이터타입: int64 /형태: (5, 2) /크기: 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 /데이터타입: int64 /형태: (3, 3, 3) /크기: 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
test1 = np.arange(1,22).reshape(3,7)
test2 = np.arange(1,8).reshape(7,1)
test3 = np.arange(1,11).reshape(5,2)
test4 = np.arange(1,22).reshape(3,7)
test5 = np.arange(1,13).reshape(4,3,1)
print(test1,"\n",'='*25)
print(test2,"\n",'='*25)
print(test3,"\n",'='*25)
print(test4,"\n",'='*25)
print(test5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [13]:
test1[1][2:5]

array([10, 11, 12])

In [14]:
print(test4[0][3:])
print(test4[1][3:])
print(test4[2][3:])

[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [15]:
test4[1:3,2:3]

array([[10],
       [17]])

In [16]:
test4

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [17]:
test4[0:3,3:7]

array([[ 4,  5,  6,  7],
       [11, 12, 13, 14],
       [18, 19, 20, 21]])

In [18]:
test4[1:3,4:6]

array([[12, 13],
       [19, 20]])

In [19]:
print(test4 > 12)
print(test4[test4 > 12])
print(test4 % 2 == 0)
print(test4[test4 % 2 == 0])

[[False False False False False False False]
 [False False False False False  True  True]
 [ True  True  True  True  True  True  True]]
[13 14 15 16 17 18 19 20 21]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]
[ 2  4  6  8 10 12 14 16 18 20]


In [20]:
# np 배열 연산 // shape 가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [21]:
# 브로드캐스팅
np3 = np1 + 10
print(np1)
print(np3)

[ 6  7  8  9 10]
[16 17 18 19 20]


In [22]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(3,1)
print(br1)
print(br2)
# 스칼라와 연산
print("=====스칼라와 연산=====")
print(br1)
print(br1+3)
print(br1*2)
# 2D와 1D의 연산
print("=====2D와 1D의 연산=====")
print(br2)
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11]
 [22]
 [33]]
=====스칼라와 연산=====
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=====2D와 1D의 연산=====
[[11]
 [22]
 [33]]
[[12 13 14]
 [26 27 28]
 [40 41 42]]
[[ 11  22  33]
 [ 88 110 132]
 [231 264 297]]


In [23]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten()) # flatten은 일자로 쭉 펴줌

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [24]:
# randomint
import numpy as np
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[111,  66, 185],
        [211, 254,  57],
        [ 60,  84, 166]],

       [[  2,  23,  72],
        [145,  45,  94],
        [210, 112, 147]],

       [[167, 103, 101],
        [108, 110,  47],
        [226,  48, 243]]], dtype=int32)

In [25]:
print('평균값:',np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 118.4074074074074 표준편차: 68.2610779283856 최소값: 2 최대값: 254


In [18]:
size=(10,5)
x = np.random.randint(1,5,size=size) # 1에서 5까지 난수
x
# print(np.mean(x))

array([[2, 2, 2, 1, 2],
       [4, 3, 3, 4, 2],
       [1, 4, 2, 3, 4],
       [4, 2, 2, 3, 1],
       [4, 2, 3, 3, 4],
       [3, 2, 2, 1, 2],
       [1, 3, 4, 2, 2],
       [4, 1, 3, 1, 2],
       [1, 2, 1, 2, 2],
       [4, 1, 4, 2, 4]], dtype=int32)

In [19]:
x = np.random.rand(10,5)
x
# print(np.mean(x))

array([[0.82632519, 0.51830946, 0.47550335, 0.39798284, 0.40953083],
       [0.13193604, 0.23101142, 0.24915649, 0.94815841, 0.42708115],
       [0.05799232, 0.15336   , 0.52150361, 0.66738313, 0.16634798],
       [0.66409972, 0.87814068, 0.50792343, 0.73686075, 0.43353384],
       [0.85547813, 0.11721371, 0.7216929 , 0.89195115, 0.99476584],
       [0.16413692, 0.63547356, 0.33036975, 0.10670233, 0.30425801],
       [0.08843712, 0.67477276, 0.01929433, 0.83828311, 0.99003686],
       [0.43207596, 0.48008295, 0.18539071, 0.42624582, 0.04939882],
       [0.32101573, 0.01008575, 0.63172554, 0.25758275, 0.20917766],
       [0.62523126, 0.12119809, 0.29203615, 0.58913032, 0.55863135]])

In [21]:
x = np.random.normal(5,3,(10,5)) # 평균이 , 표준편차 3
print(x)
print(np.mean(x),np.std(x),x.min(),x.max())

[[ 5.29627937  8.49041831  4.26566724  0.99826892  7.5711118 ]
 [ 6.14354312  9.0542503   4.9113203   2.71415643  6.71225265]
 [-2.62596591  5.53613915  4.17065981  0.96350918 -0.26935548]
 [ 0.95144217  0.94390738  5.47445537  6.46439931  2.47626092]
 [ 5.47625809  4.90926839  4.35793725  3.77395839 10.04481919]
 [ 6.61115628  6.03529946  0.04543933 10.68750984  1.2916719 ]
 [ 9.86148826  5.40026622  8.10858148  9.90967363  2.56563982]
 [ 2.74664032  9.31769767  9.61678223  0.49236815  4.00757162]
 [ 5.19943154  5.24262905  6.95634889  5.83676078  6.80695366]
 [ 3.828747    7.61662737 10.0324445   7.36190659  5.0838673 ]]
5.189369291003959 3.108330120816885 -2.625965908502833 10.687509838428571


In [25]:
x = np.random.randn(10,5)
print(x)
print(x, np.mean(x), np.std(x),x.min(),x.max())

[[-0.80901288 -1.05589545 -1.10683944  0.36928362 -0.56226501]
 [-0.73990065  0.20575659  0.21319111 -1.19681143 -1.2474442 ]
 [ 0.17427556 -0.49054355  0.75025261 -1.10881841  1.16950518]
 [ 0.92478219 -0.13720992 -0.6880841   0.55164002 -1.21742273]
 [ 1.21682695  0.44021576 -0.05690466  0.21108392  0.32077812]
 [ 0.80698251  0.25791087  1.15843979  0.57646648  0.30245609]
 [ 1.61797389 -0.64480559  0.3778407   0.6921928   1.88815325]
 [ 1.64710094  0.71402266  0.86956378 -0.49127956 -1.96401609]
 [ 0.99571179 -1.76032269 -1.55405892 -1.45996453  0.22687528]
 [-1.65217736  1.35440385 -1.30774412 -0.76805804 -0.15623323]]
[[-0.80901288 -1.05589545 -1.10683944  0.36928362 -0.56226501]
 [-0.73990065  0.20575659  0.21319111 -1.19681143 -1.2474442 ]
 [ 0.17427556 -0.49054355  0.75025261 -1.10881841  1.16950518]
 [ 0.92478219 -0.13720992 -0.6880841   0.55164002 -1.21742273]
 [ 1.21682695  0.44021576 -0.05690466  0.21108392  0.32077812]
 [ 0.80698251  0.25791087  1.15843979  0.57646648  0.3

In [28]:
x = np.array([3,4,45,43,65,0,0,0,24362,6,45,6,432,562])
print('x의 개수',len(x))
print('x의 개수',np.count_nonzero(x))
print('x의 개수',len(x) - np.count_nonzero(x))

x의 개수 14
x의 개수 11
x의 개수 3


In [30]:
print(np.mean(x))
print(x.mean())
print(np.var(x))
print(x.var())
print(np.std(x))
print(x.std())
print(x.max())
print(x.min())
print(np.median(x))

1826.642857142857
1826.642857142857
39093356.8010204
39093356.8010204
6252.468056777291
6252.468056777291
24362
0
24.5


In [31]:
print(np.percentile(x,0)) # 최소값
print(np.percentile(x,25)) # 제1사분위수
print(np.percentile(x,50)) # 중앙값, 제2사분위수
print(np.percentile(x,75)) # 제3사분위수
print(np.percentile(x,100)) # 최대값

0.0
3.25
24.5
60.0
24362.0


In [26]:
print(len(x.flatten()))

27


In [33]:
import numpy as np
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5,34,3,3,23,0,1,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
22


## 판다스(pandas)

- 시리즈(series) # 단수, 하나만 있을때
- 데이터프레임(dataframe) # 복수, 여러개 있을때

In [2]:
# !pip install pandas

In [4]:
import numpy as np
import pandas as pd # 여기서 오류가 안나야 설치된것

In [28]:
# 판다스 기초(넘파이값 넣을수있음을 알기)
data1 =np.arange(1,6)
print(data1)
data2 = pd.Series(data1)
print(data2, type(data2), data2.index, data2.values, data2.dtype) # 왼쪽은 데이터 레이블(인덱스), 오른쪽은 데이터 시리즈(벨류값)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=5, step=1) [1 2 3 4 5] int64


In [13]:
# dir(data2) # 쓸수있는 기능 조회가능

In [21]:
# 판다스 시리즈의 데이터타입
data3 = pd.Series([1,2,3.14,4,5]) # 하나의 데이터 값이 다르면 그 데이터 값을 기준으로 맞춤
# data3 = pd.Series([1,2,3,4,5], dtype="float")
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
dtype: float64


In [19]:
# 판다스 시리즈의 인덱스설정
data3 = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [41]:
# 판다스 시리즈 딕셔너리데이터
population_dict = { # 딕셔너리 준비한 것
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
# population_dict.keys() # 이건 함수임(밑에 country.index이건 속성, 다른거임,()가 쳐져있는거랑 아닌거랑 유심히 보기)
# population_dict.values()
# population_dict.items()
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근방법
# print(country['japan'])
print(country.loc['japan']) # loc는 location이라는 뜻, 위에 애랑 값은 똑같이 나오지만 그래도 loc 찍어주기
print(country.iloc[1])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
12622
12622


In [43]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['A','B','C'])
df # 가로는 컬럼, 세로는 인덱스

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [1]:
# 테스트
import numpy as np
import pandas as pd
# 두개의 시리즈 데이터
print("인구수 시리즈 데이터:")
population_dict = { # 딕셔너리 준비한 것
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
population = pd.Series(population_dict)
print(population)

print("GDP 시리즈 데이터:")
GDP_dict = { # 딕셔너리 준비한 것
    'korea':169320000,
    'japan':516700000,
    'china':140925000,
    'usa':2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('='*25)
print("데이터 프레임 생성:")
country = pd.DataFrame({'population':population,'gdp':GDP}) # 컬럼의 타이틀이 됨
country.index.name = "Country" # 인덱스 이름을 지정 # 속성에다 네임을 더 추가한다 생각하기
country.columns.name = "Info" # 컬럼 이름 지정
print(country.index, country.columns)
print(country.values, country.shape, country.size, "차원:",country.ndim) # shape에 (4, 2) 값이 나오는건 컬럼값이 2개라는 뜻

인구수 시리즈 데이터:
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터:
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성:
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]] (4, 2) 8 차원: 2


In [2]:
# 데이터 프레임의 요소 접근 방법, loc, iloc
country.loc['korea'], country.loc['usa'] # loc는 키값을 기반으로 # 시리즈는 여기서 loc없어도 값 나오는데 데이터프레임은 안됨
country.iloc[2], country.iloc[1] # iloc는 인덱스를 기반으로

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [3]:
country

Info     population         gdp
Country                        
korea          5182   169320000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [4]:
country.loc['korea':'japan',:'population'] # 주의: <= x <=

Info     population
Country            
korea          5182
japan         12622

In [5]:
country.iloc[0:2,:1] # 주의: <= x <

Info     population
Country            
korea          5182
japan         12622

In [6]:
country.iloc[1:4,1:2]

Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000

In [7]:
country.iloc[1:3,:2]

Info     population        gdp
Country                       
japan         12622  516700000
china        141178  140925000

In [8]:
# 컬럼추가(열추가) - 세로줄
# country['test']=[11,22,33,44]
# country.drop('test',axis=1) # axis는 축, 행(가로줄)이 0이고 열(세로줄)이 1임
gdpper = country['gdp'] / country['population']
country['gdp_per'] = gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [9]:
# 행추가 방법1 - 가로줄
country.loc['india'] = [142222,150505000,1212121]
country.loc['india','gdp_per'] = country.loc['india','gdp']/country.loc['india','population']
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326
india        142222   150505000   1058.239935

In [10]:
# 행추가 방법2 - 가로줄
africa = pd.Series( data = [123456,7777777], index=['population','gdp'])
country.loc['afirca'] = africa
# country.loc['africa','gdp_per'] = country.loc['africa','gdp']/country.loc['africa','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935
afirca     123456.0  7.777777e+06           NaN

In [11]:
# 결측값(NaN) 확인하는 방법
country.isnull()#.sum()

Info     population    gdp  gdp_per
Country                            
korea         False  False    False
japan         False  False    False
china         False  False    False
usa           False  False    False
india         False  False    False
afirca        False  False     True

In [ ]:
# 열제거 drop(이름, axis=0)
country = country.drop('africa', axis=0) # inplace = True 얘는 원본을 건드리는 애라 앞에 country = 이거 안넣어도 됨
country

In [13]:
# 테스트1 조건
country = [country['population']> 140000]

In [ ]:
# 테스트 2 조건 , 슬라이싱(loc,iloc 필수)
country[(country['population']> 10000) & (country['population'] < 100000)].loc[:,:'population']

In [31]:
# 문제 1
import numpy as np
import pandas as pd

print("국어 성적 데이터:")
korean_score = {
    '홍길동':80,
    '박철수':60,
    '김영희':70
}
ks = pd.Series(korean_score)
print(ks)

print("수학 성적 데이터:")
math_score = {
    '홍길동':70,
    '박철수':70,
    '김영희':90
}
ms = pd.Series(math_score)
print(ms)

print("영어 성적 데이터:")
english_score = {
    '홍길동':80,
    '박철수':80,
    '김영희':80
}
es = pd.Series(english_score)
print(es)

print('='*25)
print("데이터 프레임 생성:")
school = pd.DataFrame({ '국어':ks, '수학':ms, '영어':es})
school.columns.name = "이름"
school

국어 성적 데이터:
홍길동    80
박철수    60
김영희    70
dtype: int64
수학 성적 데이터:
홍길동    70
박철수    70
김영희    90
dtype: int64
영어 성적 데이터:
홍길동    80
박철수    80
김영희    80
dtype: int64
데이터 프레임 생성:


이름   국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [32]:
school.iloc[1:2,:2]

이름   국어  수학
박철수  60  70

In [33]:
school[school['수학'] >= 70]

이름   국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [34]:
scoper = (school['국어']+school['수학']+school['영어']) / 3
school['평균'] = scoper
school

이름   국어  수학  영어         평균
홍길동  80  70  80  76.666667
박철수  60  70  80  70.000000
김영희  70  90  80  80.000000

In [35]:
최자바 = pd.Series( data = [55,95,70], index=['국어','수학','영어'])
school.loc['최자바']=최자바
# school.loc['최자바','평균'] = school.loc['최자바','국어'+'수학'+'영어']/3
school

이름     국어    수학    영어         평균
홍길동  80.0  70.0  80.0  76.666667
박철수  60.0  70.0  80.0  70.000000
김영희  70.0  90.0  80.0  80.000000
최자바  55.0  95.0  70.0        NaN

In [77]:
# 기본적인 방법
data = {
    '이름':['홍길동','박철수','김영희'],
    '국어':[80,60,70],
    '수학':[70,70,90],
    '영어':[90,80,80]
}
df = pd.DataFrame(data)
df

이름  국어  수학  영어
0  홍길동  80  70  90
1  박철수  60  70  80
2  김영희  70  90  80

In [78]:
# 키값쌍으로 리스트에 저장하는 방법
data = [
    {'이름':'홍길동','국어':80, '수학':70, '영어':80},
    {'이름':'박철수','국어':60, '수학':70, '영어':80},
    {'이름':'김영희','국어':70, '수학':90, '영어':80}]
df = pd.DataFrame(data)
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [79]:
# 리스트에 튜플로 저장하는 방법
data = [
    ('홍길동',80,70,80),
    ('박철수',60,70,80),
    ('김영희',70,90,80)]
df = pd.DataFrame(data,columns=['이름','국어','수학','영어'])
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [80]:
import numpy as np
# data0 = [
#     ('홍길동',80,70,80),
#     ('박철수',60,70,80),
#     ('김영희',70,90,80)]
# data = np.array(data0)
data = np.array([['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80]]) # 위에꺼랑 다르게 속도 빠름
df = pd.DataFrame(data,columns=['이름','국어','수학','영어'])

In [81]:
# 1
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [82]:
# 2
df.iloc[1:2,:3]

이름  국어  수학
1  박철수  60  70

In [83]:
df.loc[1:1,:'수학'] # 앞에 인덱스 때문에 이렇게 가능(?)

이름  국어  수학
1  박철수  60  70

In [84]:
# 3
# print(df['국어'].dtype)
df[df['국어'].astype(int)>=70] # 데이터타입을 int로 바꿔줘야 계산이 됨

이름  국어  수학  영어
0  홍길동  80  70  80
2  김영희  70  90  80

In [86]:
# 4
df['평균'] = (df['국어'].astype(int) + df['수학'].astype(int) + df['영어'].astype(int))/3
print('평균',df['평균'].dtype)
df.round()

평균 float64


이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0

In [66]:
# 5
# iloc, loc # iloc가 인덱스 기준이라 iloc가 더 빠름
# df.iloc[3] = ('최자바',55,95,70,77) # 근데 iloc는 수정할수없음(?)
df.loc[3] = ('최자바',55,95,70,77) # 수정할때는 loc
df

이름  국어  수학  영어         평균
0  홍길동  80  70  80  76.666667
1  박철수  60  70  80  70.000000
2  김영희  70  90  80  80.000000
3  최자바  55  95  70  77.000000